groups:
  - name: osmo-stp.rules
    rules:
      - alert: OsmoSTPPushGatewayDown
        expr: up{job="osmo-stp"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Osmo STP Push Gateway down on {{ $labels.instance }}"
          description: "Prometheus target for osmo-stp (job=\"osmo-stp\") Push Gateway is down for more than 1 minute."

      - alert: OsmoSTPDown
        expr: status{job="osmo-stp"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Osmo STP down on {{ $labels.instance }}"
          description: "Prometheus target for osmo-stp (job=\"osmo-stp\") is down for more than 1 minute."
