groups:
  - name: osmo-bsc.rules
    rules:
      - alert: OsmoBSCPushGatewayDown
        expr: up{job="osmo-bsc"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Osmo BSC Push Gateway down on {{ $labels.instance }}"
          description: "Prometheus target for osmo-bsc (job=\"osmo-bsc\") Push Gateway is down for more than 1 minute."

      - alert: OsmoBSCDown
        expr: status{job="osmo-bsc"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Osmo BSC down on {{ $labels.instance }}"
          description: "Prometheus target for osmo-bsc (job=\"osmo-bsc\") is down for more than 1 minute."
