groups:
  - name: osmo-hlr.rules
    rules:
      - alert: OsmoHLRPushGatewayDown
        expr: up{job="osmo-hlr"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Osmo HLR Push Gateway down on {{ $labels.instance }}"
          description: "Prometheus target for osmo-hlr (job=\"osmo-hlr\") Push Gateway is down for more than 1 minute."

      - alert: OsmoHLRDown
        expr: status{job="osmo-hlr"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Osmo HLR down on {{ $labels.instance }}"
          description: "Prometheus target for osmo-hlr (job=\"osmo-hlr\") is down for more than 1 minute."
